name: Build Windows Executable

on:
  push:
    branches:
      - main  # Puedes cambiar 'main' por la rama que prefieras

jobs:
  build:
    runs-on: windows-latest  # Usará un runner de Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12  # Asegúrate de que la versión coincida con la que necesitas

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "Inventario_maisi" main.py

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: Inventario_maisi
        path: dist/Inventario_maisi.exe
