version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    runtime: nvidia
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_KEEP_ALIVE=30m
   
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 15

  llm:
    build: ./Servicios/LLM
    environment:
      - OLLAMA_HOST=http://ollama:11434/
      - LLM_MODEL=llama3.1:70b-instruct-q4_K_M
      - LLM_MAX_TOKENS=512
      - LLM_TEMPERATURE=0.2
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  ollama:
